#!/usr/bin/env python3
"""Render the decision record's tables from the manifest, between two markers in the record.

Usage: render_tables.py --write <record.md> | --check <record.md>
The tables are never edited by hand: rebuild the manifest (assemble_manifest.py), then run this with --write.
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
BEGIN, END = "<!-- tables:begin (generated by render_tables.py; do not edit) -->", "<!-- tables:end -->"


def cell(row):
    if not row["default"]:
        return "Not installed: none today"
    default = ("**" + row["default"] + "**") if row["definitive"] else row["default"]
    if row["installs_nothing_extra"] and not row["default"].lower().startswith("not installed"):
        default += " (nothing additional installed)"
    return default


def basis(row, combined):
    resolution = row["resolution"] or {}
    outcome = resolution.get("outcome")
    if outcome == "final":
        total = combined[row["layer_id"]]["gpt_samples_present"]
        votes = "2" if total == 2 else "at least 2"
        return f"both families: the Claude record and {votes} of {total} blind GPT samples"
    if outcome == "split":
        return f"{resolution['by']} disagree; measurement {resolution['measurement_id']} decides"
    if row["measurement"]:
        if row["measurement"]["returned"]:
            return row["label"].split(":")[0]
        if row["slot_id"] == "memory-owner":
            return "waiting for the memory head-to-head, at the user's request"
        return "waiting for the code-search measurement and its symmetric decision rule"
    if outcome == "not_installed":
        covered = resolution["covered_by"]
        cover = "not needed" if covered == "not needed" else "covered by " + ", ".join(covered)
        return resolution["by"] + "; " + cover
    if outcome == "installed_on_critic":
        return resolution["by"] + ": " + resolution["reason"]
    return resolution.get("reason") or row["label"]


def layer_table(man, catalog, combined):
    by = {}
    for row in man["slots"]:
        if row["catalog"] == catalog:
            by.setdefault(row["layer_id"], []).append(row)
    out = ["| Layer | Slot | Job | Default | State | Basis |", "| --- | --- | --- | --- | --- | --- |"]
    for layer in man["layers"]:
        if layer["catalog"] != catalog:
            continue
        lid, rows = layer["layer_id"], by.get(layer["layer_id"], [])
        if not rows:
            own = "; ".join(layer["owns"]) if layer["owns"] else "no tool of its own"
            out.append(f"| {lid} | | {own}. Uses: {'; '.join(u.split(' (')[0] for u in layer['uses'])} | Nothing additional installed | | ownership map |")
            continue
        for row in rows:
            out.append(f"| {lid} | {row['slot_id']} | {row['job']} | {cell(row)} | {row.get('state') or 'open'} | {basis(row, combined)} |")
    return out


def render():
    man = json.loads((HERE / "definitive-manifest.json").read_text(encoding="utf-8"))
    fnd = json.loads((HERE / "foundation-definitive.compact.json").read_text(encoding="utf-8"))
    combined = {layer["layer_id"]: layer for layer in json.loads((ROOT / man["sources"]["combined"]["path"]).read_text(encoding="utf-8"))["rows"]}
    counts = man["counts"]
    lines = [BEGIN, "",
             f"{counts['layers']} layers, {counts['slots']} slots, {counts['definitive']} definitive, {counts['installed']} rows that install something. "
             "A default in bold is definitive under its recorded rule; a critic's install verdict is resolved, and a pending measurement installs nothing.", "",
             "### Foundation and cross rows", ""]
    lines += layer_table(man, "foundation", combined)
    lines += ["", "### us-equities (the trading lane's rows)", ""]
    lines += layer_table(man, "us-equities", combined)
    lines += ["", "### The six slots of the foundation's decision round", "",
              "| Slot | Default | Blind-round or measured basis | Claude family | GPT family | Definitive | Job | State | Current basis |",
              "| --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
    rows = {row["slot_id"]: row for row in man["slots"] if row["catalog"] == "foundation"}
    for layer in fnd["layers"]:
        for slot in layer["slots"]:
            if slot["row_kind"] == "judged":
                row = rows[slot["slot_id"]]
                # The family columns are the manifest's current status; the blind round's own basis stays in the third column.
                statuses = {family: row[family] for family in ("claude", "gpt")}
                if slot.get("split") and row["measurement"] and row["measurement"]["returned"]:
                    for pick in slot["split_between"]:
                        statuses[pick["family"]] += f" on {pick['name']} in the blind round"
                blind_basis = row["resolution"].get("first_round_record", row)["label"]
                lines.append(f"| {slot['slot_id']} | {row['default']} | {blind_basis} | {statuses['claude']} | {statuses['gpt']} | "
                             f"{'yes' if row['definitive'] else 'no'} | {row['job']} | {row.get('state') or 'open'} | {basis(row, combined)} |")
                if slot.get("split_note") and not (row["measurement"] and row["measurement"]["returned"]):
                    lines.append(f"| | | {slot['split_note']} | | | | | | |")
    lines += ["", END]
    return "\n".join(lines)


if __name__ == "__main__":
    mode, record = sys.argv[1], Path(sys.argv[2])
    text = record.read_text(encoding="utf-8")
    a, b = text.index(BEGIN), text.index(END) + len(END)
    new = text[:a] + render() + text[b:]
    if mode == "--write":
        record.write_text(new, encoding="utf-8")
        print("tables written")
    elif new != text:
        print("the record's tables are stale: run render_tables.py --write")
        sys.exit(1)
    else:
        print("the record's tables are current")
