#!/usr/bin/env python3
"""Render the decision record's tables from the manifest, between two markers in the record.

Usage: render_tables.py --write <record.md> | --check <record.md>
The tables are never edited by hand: rebuild the manifest (assemble_manifest.py), then run this with --write.
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
BEGIN, END = "<!-- tables:begin (generated by render_tables.py; do not edit) -->", "<!-- tables:end -->"
STATUS = {"judged": "decision round", "first_round": "first round", "pinned": "pinned by the user", "project_practice": "project practice",
          "no_blind_default_today": "no blind default today"}


def cell(row):
    if not row["default"]:
        return "none today"
    return ("**" + row["default"] + "**") if row["definitive"] else row["default"]


def layer_table(man, catalog):
    by = {}
    for row in man["slots"]:
        if row["catalog"] == catalog:
            by.setdefault(row["layer_id"], []).append(row)
    out = ["| Layer | Default per slot | How decided |", "| --- | --- | --- |"]
    for layer in man["layers"]:
        if layer["catalog"] != catalog:
            continue
        lid, rows = layer["layer_id"], by.get(layer["layer_id"], [])
        if not rows:
            own = "; ".join(layer["owns"]) if layer["owns"] else "no tool of its own"
            out.append(f"| {lid} | {own}. Uses: {'; '.join(u.split(' (')[0] for u in layer['uses'])} | ownership map |")
            continue
        kinds = []
        for row in rows:
            kind = STATUS[row["row_kind"]]
            if row.get("state") == "measurement":
                kind = row["label"] if row["measurement"]["returned"] else "measurement, at the user's request"
            elif row.get("state") == "split":
                kind += ", split between the families: a measurement decides"
            elif row["row_kind"] == "judged":
                kind += ", both families" if row["definitive"] else (", Claude family; GPT " + row["gpt"].split(":")[0])
            if kind not in kinds:
                kinds.append(kind)
        out.append(f"| {lid} | {'; '.join(cell(row) for row in rows)} | {'; '.join(kinds)} |")
    return out


def render():
    man = json.loads((HERE / "definitive-manifest.json").read_text(encoding="utf-8"))
    fnd = json.loads((HERE / "foundation-definitive.compact.json").read_text(encoding="utf-8"))
    counts = man["counts"]
    lines = [BEGIN, "",
             f"{counts['layers']} layers, {counts['slots']} slots, {counts['definitive']} definitive. A default in bold is definitive: both families' deciders "
             "named it and both critics returned converged.", "",
             "### Foundation and cross rows", ""]
    lines += layer_table(man, "foundation")
    lines += ["", "### us-equities (the trading lane's rows)", ""]
    lines += layer_table(man, "us-equities")
    lines += ["", "### The six slots of the foundation's decision round", "",
              "| Slot | Default | Basis | Claude family | GPT family | Definitive |", "| --- | --- | --- | --- | --- | --- |"]
    rows = {row["slot_id"]: row for row in man["slots"] if row["catalog"] == "foundation"}
    for layer in fnd["layers"]:
        for slot in layer["slots"]:
            if slot["row_kind"] == "judged":
                fam = slot["families"]
                row = rows[slot["slot_id"]]
                statuses = {family: fam[family]["status"] for family in ("claude", "gpt")}
                if slot.get("split") and row["measurement"] and row["measurement"]["returned"]:
                    for pick in slot["split_between"]:
                        statuses[pick["family"]] += f" on {pick['name']} in the blind round"
                lines.append(f"| {slot['slot_id']} | {row['default']} | {row['label']} | {statuses['claude']} | {statuses['gpt']} | "
                             f"{'yes' if row['definitive'] else 'no'} |")
                if slot.get("split_note") and not (row["measurement"] and row["measurement"]["returned"]):
                    lines.append(f"| | | {slot['split_note']} | | | |")
    lines += ["", END]
    return "\n".join(lines)


if __name__ == "__main__":
    mode, record = sys.argv[1], Path(sys.argv[2])
    text = record.read_text(encoding="utf-8")
    a, b = text.index(BEGIN), text.index(END) + len(END)
    new = text[:a] + render() + text[b:]
    if mode == "--write":
        record.write_text(new, encoding="utf-8")
        print("tables written")
    elif new != text:
        print("the record's tables are stale: run render_tables.py --write")
        sys.exit(1)
    else:
        print("the record's tables are current")
