#!/usr/bin/env bash
# Corrected re-run of the headroom-0.38.0-recovery check after the fix-round
# blocker and major findings:
#  - blocker: the original run.sh omitted HEADROOM_WORKSPACE_DIR,
#    HEADROOM_OFFLINE and HEADROOM_TELEMETRY guards, so the MCP server wrote
#    into the live ~/.headroom store and made an online update check. This
#    script sets a disposable HEADROOM_WORKSPACE_DIR plus HEADROOM_OFFLINE=1
#    and HEADROOM_TELEMETRY=off, matching the guards
#    evidence/receipts/native-token-clean-prefix-20260920.json used for its
#    accepted 0.37.0 headroom-first/headroom-restart runs.
#  - major: the original run used fixtures/rag-note.md (351 bytes / 75
#    tokens), which triggered Headroom's no-op router and so never exercised
#    real compression. This run uses the larger, repetitive, owned synthetic
#    fixtures/mcp-tool-listing.json (generated by make_mcp_listing_fixture.py)
#    so the compress/retrieve round trip actually exercises a compressing
#    transform.
#
# Installs into a NEW isolated uv-tool prefix; never touches the pinned
# 0.37.0 prefix or its ~/.headroom store.
set -euo pipefail

PREFIX=/home/example/.local/share/codex-ecosystem/tools/headroom-ai-0.38.0
mkdir -p "$PREFIX/uv-tool-dir" "$PREFIX/bin"
export UV_TOOL_DIR="$PREFIX/uv-tool-dir"
export UV_TOOL_BIN_DIR="$PREFIX/bin"
export UV_PYTHON=/home/example/.local/share/codex-ecosystem/bin/python3.13

# Reuse the already-installed 0.38.0 prefix from the first (contaminated)
# run rather than reinstalling; the install step itself was not implicated
# by either finding and reinstalling would not change that evidence.
HB="$PREFIX/bin/headroom"
"$HB" --version

WORKSPACE=/home/example/codex-ecosystem/state/gap-resolution-20260922/token-observation/headroom-0.38.0-check-v2/headroom-state
mkdir -p "$WORKSPACE"

export HEADROOM_WORKSPACE_DIR="$WORKSPACE"
export HEADROOM_OFFLINE=1
export HEADROOM_TELEMETRY=off
export HEADROOM_DISABLE_KOMPRESS=1
export HEADROOM_DETECT_BACKEND=python
export HEADROOM_BINARIES_OFFLINE=1
export HF_HUB_OFFLINE=1
export TRANSFORMERS_OFFLINE=1
export LITELLM_LOCAL_MODEL_COST_MAP=True
export HEADROOM_MCP_CLIENT=gap-resolution-20260922-0.38.0-recovery-v2

FIXTURE=/home/example/code/nas-wt-gap-token-observation/blueprints/gap-resolution-20260922/headroom-0.38.0-recovery/mcp-tool-listing.json

OUT=${1:-/home/example/codex-ecosystem/state/gap-resolution-20260922/token-observation/headroom-0.38.0-check-v2}
mkdir -p "$OUT"

# The fixture (~180KB) overflows argv when JSON-inlined via --args (mcporter
# failed with "Argument list too long"), so pass it with mcporter's
# key=@path file-read syntax instead of embedding it on the command line.
# mcporter's call-argument parser (0.13.13) unconditionally consumes the
# first bare positional token as a "selector" even when --tool is already
# given by flag, which swallowed the lone "content=@..." token and produced
# "Input validation error: 'content' is a required property" (confirmed by
# manual reproduction on the small rag-note.md fixture too). A leading dummy
# positional token absorbs that selector slot so the real key=value token is
# parsed normally afterward; confirmed against
# mcp_compact_json_baseline-shaped output before wiring into this script.
mcporter call --stdio "$HB" --stdio-arg mcp --stdio-arg serve \
  --stdio-arg --proxy-url --stdio-arg http://127.0.0.1:1 \
  --name headroom038checkv2 --tool headroom_compress \
  --output json --no-oauth _dummy "content=@${FIXTURE}" > "$OUT/compress.json"

HASH=$(python3 -c "import json; print(json.load(open('$OUT/compress.json'))['hash'])")

mcporter call --stdio "$HB" --stdio-arg mcp --stdio-arg serve \
  --stdio-arg --proxy-url --stdio-arg http://127.0.0.1:1 \
  --name headroom038checkv2 --tool headroom_retrieve \
  --args "{\"hash\":\"$HASH\"}" --output json --no-oauth > "$OUT/retrieve.json"

mcporter call --stdio "$HB" --stdio-arg mcp --stdio-arg serve \
  --stdio-arg --proxy-url --stdio-arg http://127.0.0.1:1 \
  --name headroom038checkv2 --tool headroom_stats \
  --args '{}' --output json --no-oauth > "$OUT/stats.json"

python3 -c "
import json, hashlib
orig = open('$FIXTURE').read()
retrieved = json.load(open('$OUT/retrieve.json'))['original_content']
print('exact_match:', orig == retrieved)
print('orig_sha256:', hashlib.sha256(orig.encode()).hexdigest())
print('retrieved_sha256:', hashlib.sha256(retrieved.encode()).hexdigest())
"

echo "post-run: asserting the live default ~/.headroom store was not touched by this run"
