#!/bin/sh
# Local integration checks; no installs, downloads or model execution.
# Source/lifecycle references: ../../security-repair-sources.md.
# Optional argument: an original lock copy. Otherwise read the recorded Git blob.
set -eu

here=$(cd "$(dirname "$0")" && pwd)
check=$(mktemp -d)
trap 'rm -rf "$check"' EXIT
trap 'exit 130' INT TERM
mkdir "$check/tmp" "$check/bin" "$check/repo" "$check/repo/.git"
export TMPDIR="$check/tmp"
say() { printf '%s\n' "$*"; }
fail() { say "FAIL: $*"; exit 1; }
expect_status() { [ "$1" -eq "$2" ] || fail "exit $1, expected $2"; say "exit $1 (expected)"; }
clean_tmp() {
  [ -z "$(ls -A "$TMPDIR")" ] || fail "temporary workspace leaked"
  say "temporary workspace entries: 0"
}
digest() { sha256sum < "$1" | cut -d' ' -f1; }

if [ "$#" -gt 0 ]; then
  original=$1
else
  revision=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["original_lock"]["git_revision"])' "$here/environment-record.json")
  original=$check/original.txt
  git -C "$here" show "$revision:blueprints/trials-20260926/colpali/reproduction/requirements-lock.txt" > "$original"
  say "original lock source: Git revision $revision (historical blob)"
fi
say "original lock: $(wc -c < "$original") bytes, sha256 $(digest "$original")"
say "environment-record.json sha256 $(digest "$here/environment-record.json")"

say "== no opt-in: advisory IDs printed, exit 2, no files"
status=0
python3 "$here/regenerate_lock.py" > "$check/no-opt.stdout" 2> "$check/no-opt.stderr" || status=$?
expect_status "$status" 2
cat "$check/no-opt.stderr"
[ ! -s "$check/no-opt.stdout" ] || fail "refusal printed a lock path"
clean_tmp

say "== explicit opt-in: warning and byte-identical lock"
python3 "$here/regenerate_lock.py" --accept-known-advisories > "$check/lock-path" 2> "$check/accepted.stderr"
cat "$check/accepted.stderr"
grep -q 'WARNING:' "$check/accepted.stderr" || fail "warning missing"
lock=$(cat "$check/lock-path")
cmp "$lock" "$original" || fail "regenerated bytes differ from original"
say "regenerated: $(wc -c < "$lock") bytes, sha256 $(digest "$lock")"
say "cmp: regenerated lock is byte-identical to the original"
python3 - "$here/environment-record.json" "$check/no-opt.stderr" "$check/accepted.stderr" <<'PY'
import json, sys
from pathlib import Path
record = json.loads(Path(sys.argv[1]).read_text())
for output in sys.argv[2:]:
    text = Path(output).read_text()
    assert all(identifier in text for item in record['known_advisories']['advisories'] for identifier in item['ids'])
print('PASS: all recorded advisory IDs printed on both paths')
PY
rm -rf "$(dirname "$lock")"
clean_tmp

say "== temporary root inside a Git work tree: refused"
status=0
TMPDIR="$check/repo" python3 "$here/regenerate_lock.py" --accept-known-advisories > "$check/repo.stdout" 2> "$check/repo.stderr" || status=$?
expect_status "$status" 2
tail -n 1 "$check/repo.stderr"
[ ! -s "$check/repo.stdout" ] || fail "repository refusal printed a lock path"
[ "$(find "$check/repo" -type f | wc -l)" -eq 0 ] || fail "wrote inside a Git work tree"

say "== altered pin: mismatch before writing"
sed 's/"line": "torch==2.8.0"/"line": "torch==2.8.1"/' "$here/environment-record.json" > "$check/tampered.json"
status=0
python3 "$here/regenerate_lock.py" --accept-known-advisories --record "$check/tampered.json" > "$check/tampered.stdout" 2> "$check/tampered.stderr" || status=$?
expect_status "$status" 1
grep 'MISMATCH:' "$check/tampered.stderr"
clean_tmp

say "== altered structured version: mismatch before writing"
sed 's/"version": "2.8.0"/"version": "2.8.1"/' "$here/environment-record.json" > "$check/tampered-fields.json"
status=0
python3 "$here/regenerate_lock.py" --accept-known-advisories --record "$check/tampered-fields.json" > /dev/null 2> "$check/fields.stderr" || status=$?
expect_status "$status" 1
grep 'MISMATCH:' "$check/fields.stderr"
clean_tmp

say "== reproduce-cpu.sh without opt-in: no output directory"
status=0
sh "$here/reproduce-cpu.sh" "$check/refused-out" > "$check/refused.log" 2>&1 || status=$?
expect_status "$status" 2
[ ! -e "$check/refused-out" ] || fail "output directory created without opt-in"
grep -q 'PYSEC-2025-203' "$check/refused.log" || fail "advisory IDs missing"
clean_tmp

# Synthetic uv: exercises the real install/freeze comparison, then stops before
# any model execution. It never installs a package or accesses a service.
cat > "$check/bin/uv" <<'SH'
#!/bin/sh
case "$1 $2" in
  'venv --python')
    [ "$STUB_MODE" != venv-fail ] || exit 1
    mkdir -p "$4/bin"
    printf '#!/bin/sh\nexit 1\n' > "$4/bin/python"
    chmod 0755 "$4/bin/python"
    ;;
  'pip install') [ -f "$6" ] || exit 1 ;;
  'pip freeze')
    if [ "$STUB_MODE" = mismatch ]; then
      printf 'torch==0.0.0\n'
    else
      cat "$STUB_ORIGINAL"
    fi
    ;;
  *) exit 99 ;;
esac
SH
chmod 0755 "$check/bin/uv"
export STUB_ORIGINAL="$original"
for mode in venv-fail equal mismatch; do
  say "== reproduce-cpu.sh opt-in, synthetic uv mode: $mode"
  status=0
  PATH="$check/bin:$PATH" STUB_MODE="$mode" sh "$here/reproduce-cpu.sh" --accept-known-advisories "$check/out-$mode" > "$check/$mode.log" 2>&1 || status=$?
  expect_status "$status" 1
  grep -q 'WARNING:' "$check/$mode.log" || fail "CPU script did not surface warning"
  case "$mode" in
    venv-fail) grep -q 'FAIL: uv venv' "$check/out-$mode/steps.log" ;;
    equal)
      grep -q 'installed set equals environment-record.json' "$check/out-$mode/steps.log"
      grep -q 'FAIL: device check' "$check/out-$mode/steps.log"
      ;;
    mismatch) grep -q 'FAIL: installed set differs from environment-record.json' "$check/out-$mode/steps.log" ;;
  esac
  cut -d' ' -f2- "$check/out-$mode/steps.log"
  clean_tmp
done
say "PASS: all lock regeneration and CPU-script integration checks"
