"""The XNYS session calendar (populations.session_calendar, session_times).

data/session-calendar.json is generated by data-tools/generate_session_calendar.py from exchange_calendars 4.13.2 and
pinned by sha256 (data-pins.json; at the freeze, run_discipline.data_files). Its schema (review round 15, N01) is the
generator's: a header and a 'columns' list naming the six fields of every row of 'sessions', [session, open_et,
close_et, open_utc, close_utc, early_close]. Calendar.from_document reads exactly that schema and refuses any other
(the former loader read a {"d", "open", "close"} dictionary per session, a format no committed file has).
build_calendar writes the same schema for synthetic tests. Removals of unscheduled closures come only from
data/session-calendar-amendments.jsonl (append-only, run_discipline.amendment_format; core.logs checks the prefix
rule and the commit-time rule). Every time is epoch seconds (UTC).
"""
from __future__ import annotations

import bisect
import json
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

from pinned.rules_copy import et_epoch
from core.params import CHRONO, T

CALENDAR_SOURCE = "exchange_calendars 4.13.2 XNYS"
SCHEMA_VERSION = 1
COLUMNS = ["session", "open_et", "close_et", "open_utc", "close_utc", "early_close"]
TIMEZONE = "America/New_York"
# Review round 15, N01: the earliest lookback the study requests. A development event on the first warm-up session
# requests its daily bars from t-60 (core.plan.event_requests), which is the farthest any request reaches back.
LOOKBACK_SESSIONS = 60


class CalendarSchemaError(ValueError):
    pass


def iso_utc(ts: float) -> str:
    return datetime.fromtimestamp(ts, timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def parse_utc(text: str) -> float:
    return datetime.fromisoformat(text.replace("Z", "+00:00")).timestamp()


def build_calendar(first: str, last: str) -> dict:
    """A calendar document in the data file's schema, from the pinned exchange_calendars version (refuses any other).
    The committed data file comes from data-tools/generate_session_calendar.py; this builder serves synthetic tests
    and writes the same fields."""
    import exchange_calendars as xcals
    from zoneinfo import ZoneInfo

    if xcals.__version__ != "4.13.2":
        raise RuntimeError(f"exchange_calendars {xcals.__version__} is not the pinned 4.13.2")
    cal = xcals.get_calendar("XNYS", start=first, end=last)
    tz = ZoneInfo(TIMEZONE)
    early = {s.strftime("%Y-%m-%d") for s in cal.early_closes}
    rows = []
    for s in cal.sessions_in_range(first, last):
        d = s.strftime("%Y-%m-%d")
        o, c = cal.session_open(s).to_pydatetime(), cal.session_close(s).to_pydatetime()
        rows.append([d, o.astimezone(tz).isoformat(timespec="seconds"), c.astimezone(tz).isoformat(timespec="seconds"),
                     iso_utc(o.timestamp()), iso_utc(c.timestamp()), d in early])
    return {"schema_version": SCHEMA_VERSION, "id": "mover-v3-session-calendar", "calendar": "XNYS",
            "source": {"package": "exchange_calendars", "version": xcals.__version__,
                       "call": f"exchange_calendars.get_calendar('XNYS', start={first!r}, end={last!r}).schedule"},
            "timezone": TIMEZONE, "requested_range": {"start": first, "end": last},
            "first_session": rows[0][0], "last_session": rows[-1][0], "session_count": len(rows),
            "early_close_count": sum(1 for r in rows if r[5]), "late_open_count": 0, "columns": list(COLUMNS),
            "sessions": rows}


def _rows(doc: dict) -> list:
    """The (session, open epoch, close epoch) rows of a calendar document, after every schema check (review round
    15, N01). Refuses another schema version, calendar, source version or time zone, other columns, a malformed row,
    ET and UTC instants that differ, an open other than 09:30 ET, a close other than 16:00 ET (13:00 ET on a row
    flagged early_close), unsorted or repeated sessions, and a header whose first_session, last_session,
    session_count or early_close_count differ from the rows."""
    def refuse(msg):
        raise CalendarSchemaError(f"session calendar: {msg}")
    if not isinstance(doc, dict) or doc.get("schema_version") != SCHEMA_VERSION:
        refuse(f"schema_version must be {SCHEMA_VERSION}")
    if doc.get("calendar") != "XNYS" or doc.get("timezone") != TIMEZONE:
        refuse("calendar must be XNYS in America/New_York")
    src = doc.get("source") or {}
    if src.get("package") != "exchange_calendars" or src.get("version") != "4.13.2":
        refuse("source must be exchange_calendars 4.13.2")
    if doc.get("columns") != COLUMNS:
        refuse(f"columns must be {COLUMNS}")
    sessions = doc.get("sessions")
    if not isinstance(sessions, list) or not sessions:
        refuse("sessions must be a non-empty list of rows")
    out = []
    for i, row in enumerate(sessions):
        if not isinstance(row, list) or len(row) != len(COLUMNS) or not all(isinstance(v, str) for v in row[:5]) \
                or type(row[5]) is not bool:
            refuse(f"row {i} is not [session, open_et, close_et, open_utc, close_utc, early_close]")
        d, open_et, close_et, open_utc, close_utc, early = row
        try:
            date.fromisoformat(d)
            o_et, c_et = datetime.fromisoformat(open_et), datetime.fromisoformat(close_et)
            o_utc, c_utc = parse_utc(open_utc), parse_utc(close_utc)
        except ValueError:
            refuse(f"row {i} ({d}) has an unparseable date or time")
        if o_et.utcoffset() is None or c_et.utcoffset() is None:
            refuse(f"row {i} ({d}): open_et and close_et carry their UTC offset")
        if o_et.timestamp() != o_utc or c_et.timestamp() != c_utc:
            refuse(f"row {i} ({d}): the ET and UTC instants differ")
        if o_et.date().isoformat() != d or c_et.date().isoformat() != d:
            refuse(f"row {i} ({d}): open or close is not on the session date")
        if (o_et.hour, o_et.minute) != (9, 30) or (c_et.hour, c_et.minute) != ((13, 0) if early else (16, 0)):
            refuse(f"row {i} ({d}): open 09:30 ET and close {'13:00' if early else '16:00'} ET expected")
        if o_utc != et_epoch(d, "09:30") or c_utc != et_epoch(d, "13:00" if early else "16:00"):
            refuse(f"row {i} ({d}): the instants differ from America/New_York local time")
        out.append((d, o_utc, c_utc))
    days = [r[0] for r in out]
    if days != sorted(days) or len(set(days)) != len(days):
        refuse("sessions must be unique and sorted")
    header = (doc.get("first_session"), doc.get("last_session"), doc.get("session_count"),
              doc.get("early_close_count"))
    if header != (days[0], days[-1], len(days), sum(1 for r in sessions if r[5])):
        refuse("first_session, last_session, session_count or early_close_count differ from the rows")
    return out


class Calendar:
    def __init__(self, rows: list, removed: tuple = ()):
        """rows: (session, open epoch, close epoch), from _rows. Use from_document or from_files."""
        removed = set(removed)
        unknown = sorted(removed - {r[0] for r in rows})
        if unknown:
            raise ValueError(f"a calendar amendment removes {unknown[0]}, which is not a session of the calendar")
        rows = [r for r in rows if r[0] not in removed]
        self.days = [r[0] for r in rows]
        if self.days != sorted(self.days) or len(set(self.days)) != len(self.days):
            raise ValueError("calendar sessions must be unique and sorted")
        self._open = {r[0]: float(r[1]) for r in rows}
        self._close = {r[0]: float(r[2]) for r in rows}
        self._idx = {d: i for i, d in enumerate(self.days)}
        self.removed = tuple(sorted(removed))

    @classmethod
    def from_document(cls, doc: dict, removed: tuple = ()):
        return cls(_rows(doc), removed)

    @classmethod
    def from_files(cls, calendar_path, amendments_path=None, *, freeze_session: str | None = None):
        """The pinned calendar with its amendment lines applied. An amendment line applies only when the freeze
        session is known, and one that concerns a session before it is refused (review round 9, F5): no amendment
        can move a development, validation or pre-freeze session. Every line is checked against
        run_discipline.amendment_format (core.amendments; review round 15)."""
        from core.amendments import calendar_line_problems
        body = json.loads(Path(calendar_path).read_text(encoding="utf-8"))
        removed = []
        for i, rec in enumerate(read_amendments(amendments_path)):
            problems = calendar_line_problems(rec)
            if problems:
                raise ValueError(f"calendar amendment line {i}: {'; '.join(problems)}")
            if freeze_session is None:
                raise ValueError("a calendar amendment line applies only with the freeze session known")
            if rec["session"] < freeze_session:
                raise ValueError(f"calendar amendment concerns {rec['session']}, before the freeze session")
            removed.append(rec["session"])
        return cls.from_document(body, tuple(removed))

    def is_session(self, d: str) -> bool:
        return d in self._idx

    def index(self, d: str) -> int:
        return self._idx[d]

    def offset(self, d: str, k: int) -> str | None:
        i = self._idx[d] + k
        return self.days[i] if 0 <= i < len(self.days) else None

    def next_on_or_after(self, d: str) -> str | None:
        i = bisect.bisect_left(self.days, d)
        return self.days[i] if i < len(self.days) else None

    def range(self, first: str, last: str) -> list[str]:
        return self.days[bisect.bisect_left(self.days, first): bisect.bisect_right(self.days, last)]

    def open(self, d: str) -> float:
        return self._open[d]

    def close(self, d: str) -> float:
        return self._close[d]

    def is_early_close(self, d: str) -> bool:
        return self._close[d] < et_epoch(d, "16:00")

    def stamp_1555(self, d: str) -> float:
        """'15:55 ET' = the scheduled close minus 5 minutes (12:55 on a 13:00 early close)."""
        return self._close[d] - T["stamp_before_close_s"]

    def at(self, d: str, hhmm: str) -> float:
        return et_epoch(d, hhmm)

    def session_of_time(self, ts: float) -> str | None:
        """The first session whose scheduled open is at or after ts (chronology.holdout.window)."""
        start = (datetime.fromtimestamp(ts, timezone.utc).date() - timedelta(days=1)).isoformat()
        for d in self.days[bisect.bisect_left(self.days, start):]:
            if self._open[d] >= ts:
                return d
        return None

    def in_regular(self, d: str, ts: float) -> bool:
        return self._open[d] <= ts < self._close[d]


def session_of_time(cal: Calendar, ts: float) -> str | None:
    return cal.session_of_time(ts)


def check_study_reach(cal: Calendar) -> None:
    """Review round 15, N01: the calendar reaches the farthest lookback the study requests, 60 sessions before the
    first warm-up session (a development event on it requests its daily bars from t-60; the screen needs s-1, the
    auctions t-22 and the minute bars t-19). The end is checked where it is needed: core.holdout.window refuses a
    holdout the calendar does not reach, and core.plan refuses a request past it."""
    first = CHRONO["warmup"][0]
    if not cal.is_session(first) or cal.offset(first, -LOOKBACK_SESSIONS) is None:
        raise CalendarSchemaError(f"the session calendar does not reach {LOOKBACK_SESSIONS} sessions before {first} "
                                  f"(it starts {cal.days[0] if cal.days else None})")


def read_amendments(path) -> list:
    if not path or not Path(path).exists():
        return []
    return [json.loads(x) for x in Path(path).read_text(encoding="utf-8").splitlines() if x.strip()]


def year_of(d: str) -> int:
    return date.fromisoformat(d).year
