# Source: https://github.com/systemd/systemd/blob/b3d8fc43e9cb531d958c17ef2cd93b374bc14e8a/man/systemd.slice.xml#L54
[Slice]
# Source: https://github.com/systemd/systemd/blob/b3d8fc43e9cb531d958c17ef2cd93b374bc14e8a/man/systemd.resource-control.xml#L406
MemoryMax=64G
# Source: https://github.com/systemd/systemd/blob/b3d8fc43e9cb531d958c17ef2cd93b374bc14e8a/man/systemd.resource-control.xml#L390
MemoryHigh=infinity
