#!/usr/bin/env python3
"""Build the new-host grand list: every foundation and trading layer with its
recorded winners, their pins against upstream, per-platform E2E state, the
install profile and bootstrap pin that bring each one onto a new machine, and
the hardware tiers of the known hosts.

This is a read-only join. It never selects a winner, changes a verdict, pins a
version or records a receipt. Sources:

- ``catalogs/landscape/component-evidence-matrix.json``: winners, evidence
  class, per-platform ``e2e_state``, open ``executable_now`` gaps and the
  ``needs_host`` lists (itself generated by ``scripts/component_matrix.py``);
- ``catalogs/landscape/{foundation,us-equities}.json``: each layer's decision;
- ``catalogs/sota-convergence/manifest-20260923.json``: upstream latest release
  and ``pin_behind_upstream`` per component;
- ``adoption/manifest.json``: install profiles (setup order) and recipes;
- ``adoption/pins-linux-x86_64.json`` and ``adoption/pins-macos-arm64.json``:
  which tools each bootstrap installs from a pinned, checksummed artifact;
- ``adoption/hardware-profiles.json`` and the measured host evidence it cites:
  per-host tiers.

Modes: ``--check`` (default) recomputes both outputs and exits 1 on any
difference from the checked-in files; ``--write`` writes them.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

try:
    from . import host_receipts
    from .validate import PRIVATE_CONTENT
except ImportError:  # running as a plain script, not a package
    import host_receipts
    from validate import PRIVATE_CONTENT

ROOT = Path(__file__).resolve().parent.parent
OUT_JSON = "catalogs/landscape/new-host-grand-list.json"
OUT_MD = "docs/new-host-grand-list.md"
MANIFEST = "catalogs/sota-convergence/manifest-20260923.json"
PLATFORMS = ("linux-wsl2-x86_64", "macos-arm64")
PIN_FILES = {"linux-wsl2-x86_64": "adoption/pins-linux-x86_64.json", "macos-arm64": "adoption/pins-macos-arm64.json"}
LEDGERS = {"foundation": "catalogs/landscape/foundation.json", "us-equities": "catalogs/landscape/us-equities.json"}
# Bootstrap pin ids that name the same component under a different id.
PIN_ALIASES = {"claude-code": {"claude-code", "claude"}, "llama-cpp": {"llama-cpp", "llama.cpp"}}
# Ledger/matrix component ids that appear under a different id in adoption/manifest.json profiles.
ADOPTION_IDS = {
    "nautilustrader": "nautilus-trader", "data-alpaca-py": "alpaca-py", "data-duckdb": "duckdb",
    "data-edgartools": "edgartools", "data-exchange-calendars": "exchange-calendars",
    "foundation-ai-memory": "ai-memory", "foundation-socraticode": "socraticode",
    "candidate:cli-cli": "gh", "candidate:astral-sh-uv": "uv",
}


def load(rel: str):
    return json.loads((ROOT / rel).read_text(encoding="utf-8"))


def repo_key(url) -> str:
    if not isinstance(url, str):
        return ""
    m = re.search(r"github\.com/([^/\s#?]+)/([^/\s#?]+)", url)
    if not m:
        return url.strip().rstrip("/").lower()
    return (m.group(1) + "/" + re.sub(r"\.git$", "", m.group(2))).lower()


def manifest_index(manifest: dict) -> dict:
    index = {}
    for section in ("foundation", "trading"):
        for layer in manifest.get(section, []):
            layer_id = layer.get("layer")
            for comp in (layer.get("components") or []) + (layer.get("entries") or []) + (layer.get("candidates") or []):
                if not isinstance(comp, dict):
                    continue
                entry = {
                    "manifest_id": comp.get("id"),
                    "manifest_pin": comp.get("pin"),
                    "upstream_latest": (comp.get("upstream") or {}).get("latest"),
                    "pin_behind_upstream": comp.get("pin_behind_upstream"),
                    "pin_comparison": comp.get("pin_comparison"),
                }
                index[(layer_id, "id", comp.get("id"))] = entry
                key = repo_key(comp.get("repository"))
                if key:
                    index.setdefault((layer_id, "repo", key), entry)
    return index


def profile_index(adoption: dict) -> dict:
    out = {}
    for order, profile in enumerate(adoption.get("profiles", []), start=1):
        for comp in profile.get("component_ids", []):
            out.setdefault(comp, []).append({"order": order, "profile": profile["id"]})
    return out


def pinned_tools() -> dict:
    """Per platform: the pinned tool ids and the GitHub repositories their artifacts come from."""
    out = {}
    for platform, rel in PIN_FILES.items():
        tools = [tool for tool in load(rel).get("tools", []) if isinstance(tool, dict)]
        out[platform] = {"ids": {tool.get("id") for tool in tools},
                         "repos": {repo_key(tool.get("url")) for tool in tools if "github.com/" in str(tool.get("url"))}}
    return out


def adoption_id(component_id: str) -> str:
    return ADOPTION_IDS.get(component_id, strip_candidate(component_id))


def is_pinned(component_id: str, repository, pins_for_platform: dict) -> bool:
    bare = adoption_id(component_id)
    names = PIN_ALIASES.get(bare, {bare})
    return bool(names & pins_for_platform["ids"]) or (bool(repository) and repo_key(repository) in pins_for_platform["repos"])


def ledger_decisions() -> dict:
    out = {}
    for catalog, rel in LEDGERS.items():
        for layer in load(rel).get("layers", []):
            out[(catalog, layer.get("layer_id"))] = layer.get("decision")
    return out


def strip_candidate(component_id: str) -> str:
    return component_id.split(":", 1)[1] if component_id.startswith("candidate:") else component_id


def build() -> dict:
    matrix = load("catalogs/landscape/component-evidence-matrix.json")
    mindex = manifest_index(load(MANIFEST))
    adoption = load("adoption/manifest.json")
    profiles = profile_index(adoption)
    recipes = adoption.get("recipe_map", {})
    pins = pinned_tools()
    decisions = ledger_decisions()
    hw = load("adoption/hardware-profiles.json")

    layers = []
    for row in matrix["rows"]:
        winners = []
        for winner in row.get("winners", []):
            cid = winner["component_id"]
            bare = strip_candidate(cid)
            m = (mindex.get((row["layer_id"], "id", cid)) or mindex.get((row["layer_id"], "id", bare))
                 or mindex.get((row["layer_id"], "repo", repo_key(winner.get("repository")))) or {})
            platforms = {}
            for platform in PLATFORMS:
                state = (winner.get("platforms") or {}).get(platform) or {}
                platforms[platform] = {
                    "e2e_state": state.get("e2e_state"),
                    "bootstrap_pinned": is_pinned(cid, winner.get("repository"), pins[platform]),
                }
            winners.append({
                "component_id": cid,
                "repository": winner.get("repository"),
                "pin": winner.get("pin"),
                "evidence_class": winner.get("evidence_class"),
                "upstream_latest": m.get("upstream_latest"),
                "pin_behind_upstream": m.get("pin_behind_upstream"),
                "manifest_joined": bool(m),
                "install_profiles": [p["profile"] for p in profiles.get(adoption_id(cid), [])],
                "recipe": recipes.get(adoption_id(cid)),
                "platforms": platforms,
            })
        layers.append({
            "catalog": row["catalog"],
            "layer_id": row["layer_id"],
            "title": row["title"],
            "decision": decisions.get((row["catalog"], row["layer_id"])),
            "verdict_status": row.get("verdict_status"),
            "independent_review": row.get("independent_review"),
            "open_executable_now_gaps": row.get("open_executable_now_gaps"),
            "winners": winners,
        })

    hosts = []
    for host in hw.get("hosts", []):
        tiers = None
        if host.get("evidence_class") == "native_proven" and isinstance(host.get("evidence"), str) and host["evidence"].endswith(".json"):
            path = ROOT / host["evidence"]
            if path.is_file():
                tiers = json.loads(path.read_text(encoding="utf-8")).get("recommended")
        hosts.append({
            "id": host.get("id"),
            "label": host.get("label"),
            "evidence_class": host.get("evidence_class"),
            "assumptions": host.get("assumptions"),
            "measured_tiers": tiers,
            "sizing_arithmetic": host.get("sizing_arithmetic"),
        })

    winners_all = [w for layer in layers for w in layer["winners"]]
    summary = {
        "layers": {"foundation": sum(1 for l in layers if l["catalog"] == "foundation"),
                   "us-equities": sum(1 for l in layers if l["catalog"] == "us-equities")},
        "winners": len(winners_all),
        "winner_count_unit": "layer-winner pairs (a component that wins several layers counts once per layer)",
        "distinct_components": len({adoption_id(w["component_id"]) for w in winners_all}),
        "pins_behind_upstream": sorted({w["component_id"] for w in winners_all if w["pin_behind_upstream"] is True}),
        "not_joined_to_manifest": sorted({w["component_id"] for w in winners_all if not w["manifest_joined"]}),
        "e2e_accepted": {p: sum(1 for w in winners_all if w["platforms"][p]["e2e_state"] == "accepted") for p in PLATFORMS},
        "bootstrap_pinned": {p: sorted({w["component_id"] for w in winners_all if w["platforms"][p]["bootstrap_pinned"]}) for p in PLATFORMS},
        "needs_host": {p: len(matrix.get("summary", {}).get("needs_host", {}).get(p, [])) for p in PLATFORMS},
    }
    return {
        "schema_version": 1,
        "scope": ("Read-only join of the recorded layer winners, their pins against upstream, per-platform E2E state, "
                  "install profiles, bootstrap pins and host hardware tiers, for setting up a new WSL2 or macOS host. "
                  "It selects nothing and changes no verdict."),
        "sources": {
            "matrix": "catalogs/landscape/component-evidence-matrix.json",
            "ledgers": LEDGERS,
            "manifest": MANIFEST,
            "profiles": "adoption/manifest.json",
            "bootstrap_pins": PIN_FILES,
            "hardware": "adoption/hardware-profiles.json",
        },
        "setup_order": [{"order": i, "profile": p["id"], "label": p.get("label"), "component_ids": p.get("component_ids", [])}
                        for i, p in enumerate(adoption.get("profiles", []), start=1)],
        "hosts": hosts,
        "layers": layers,
        "summary": summary,
    }


def tier_value(value):
    """Reduce a labelled-projection arithmetic string to its result, e.g.
    'vram_gb=24 >= 20 -> large-32b-q4' -> 'large-32b-q4'; 'min(16, 32 - 2) = 16' -> '16'."""
    if not isinstance(value, str):
        return value
    if "->" in value:
        return value.rsplit("->", 1)[1].strip()
    if "=" in value:
        return value.rsplit("=", 1)[1].strip()
    return value


def md_cell(value) -> str:
    return str(value if value not in (None, "") else "—").replace("|", "\\|").replace("\n", " ")


def render_md(data: dict) -> str:
    s = data["summary"]
    lines = [
        "# New-host grand list",
        "",
        "Generated by `scripts/new_host_grand_list.py` from the component evidence matrix, the layer ledgers, "
        f"`{MANIFEST}`, `adoption/manifest.json`, the bootstrap pin files and `adoption/hardware-profiles.json`. "
        "Do not edit by hand; run `python3 scripts/new_host_grand_list.py --write`. It selects nothing: winners and "
        "verdicts change only through the lane re-record, pins only through their qualification.",
        "",
        f"Layers: {s['layers']['foundation']} foundation, {s['layers']['us-equities']} trading. Winners: {s['winners']} "
        f"layer-winner pairs ({s['distinct_components']} distinct components). Pairs accepted end to end: "
        f"{s['e2e_accepted']['linux-wsl2-x86_64']} on WSL2, {s['e2e_accepted']['macos-arm64']} on macOS. Distinct "
        f"components pinned behind upstream: {len(s['pins_behind_upstream'])}. Pairs a new host still has to prove: "
        f"{s['needs_host']['linux-wsl2-x86_64']} on WSL2, {s['needs_host']['macos-arm64']} on macOS "
        "(the `needs_host` lists in `catalogs/landscape/component-evidence-matrix.json`).",
        "",
        "## How to set up a host",
        "",
        "1. Follow [`adoption/bootstrap.md`](../adoption/bootstrap.md) from a pinned clone (step 0) through native sign-in.",
        "2. Run `python3 scripts/hardware_profile.py` and compare its tiers with the host table below.",
        "3. Install the profiles in the order below; each bootstrap installs only the tools in its pin file.",
        "4. Record what ran with [`docs/contributing-evidence.md`](contributing-evidence.md) (`scripts/host_receipts.py`).",
        "",
        "## Setup order (install profiles)",
        "",
        "| Order | Profile | Components |",
        "| --- | --- | --- |",
    ]
    for p in data["setup_order"]:
        lines.append(f"| {p['order']} | `{p['profile']}`: {md_cell(p['label'])} | {', '.join('`' + c + '`' for c in p['component_ids'])} |")
    lines += ["", "## Hosts and hardware tiers", "", "| Host | Evidence | Generation tier | Semantic-RAG tier | Concurrency cap |", "| --- | --- | --- | --- | --- |"]
    for h in data["hosts"]:
        t = h.get("measured_tiers") or {}
        a = h.get("sizing_arithmetic") or {}
        gen = t.get("local_generation_model_tier") or tier_value(a.get("local_generation_model_tier"))
        rag = t.get("embedding_semantic_rag_tier") or tier_value(a.get("embedding_semantic_rag_tier"))
        cap = t.get("workflow_concurrency_cap") or tier_value(a.get("workflow_concurrency_cap"))
        lines.append(f"| {md_cell(h['label'])} | {md_cell(h['evidence_class'])} | {md_cell(gen)} | {md_cell(rag)} | {md_cell(cap)} |")
    for catalog, title in (("foundation", "Foundation layers"), ("us-equities", "Trading layers (north star)")):
        lines += ["", f"## {title}", "",
                  "| Layer | Decision | Winner | Pin (upstream) | Evidence | WSL2 | macOS | Installed by | Open gaps |",
                  "| --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
        for layer in (l for l in data["layers"] if l["catalog"] == catalog):
            for i, w in enumerate(layer["winners"] or [None]):
                head = f"{md_cell(layer['title'])} | {md_cell(layer['decision'])}" if i == 0 else " | "
                if w is None:
                    lines.append(f"| {head} | — | — | — | — | — | — | {md_cell(layer['open_executable_now_gaps'])} |")
                    continue
                pin = md_cell(w["pin"])
                if w["pin_behind_upstream"] is True and w["upstream_latest"]:
                    pin += f" (behind {md_cell(w['upstream_latest'])})"
                cells = []
                for p in PLATFORMS:
                    st = w["platforms"][p]
                    cells.append(md_cell(st["e2e_state"]) + (", pinned" if st["bootstrap_pinned"] else ""))
                gaps = md_cell(layer["open_executable_now_gaps"]) if i == 0 else ""
                lines.append(f"| {head} | `{w['component_id']}` | {pin} | {md_cell(w['evidence_class'])} | {cells[0]} | {cells[1]} | "
                             f"{md_cell(', '.join(w['install_profiles']))} | {gaps} |")
    lines += ["", "\"pinned\" means the platform's bootstrap installs the tool from a pinned, checksummed artifact. "
              "An E2E state of `accepted` is scoped to the recorded host; a new host proves its own.",
              "", "## How to update this page", "",
              "Generated, not hand-edited. After any change to the component evidence matrix (host receipts, "
              "decisions, verdict re-records), the layer ledgers, `" + MANIFEST + "`, `adoption/manifest.json`, the "
              "bootstrap pin files or `adoption/hardware-profiles.json`, run "
              "`python3 scripts/component_matrix.py --write` and then `python3 scripts/new_host_grand_list.py --write`, "
              "and commit the outputs. `--check` runs in CI."]
    if s["not_joined_to_manifest"]:
        lines += ["", "Winners without a manifest row (no upstream comparison shown): "
                  + ", ".join("`" + c + "`" for c in s["not_joined_to_manifest"]) + "."]
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="exit 1 if the checked-in outputs differ (default)")
    mode.add_argument("--write", action="store_true", help="write the outputs")
    args = parser.parse_args(argv)
    data = build()
    outputs = {OUT_JSON: json.dumps(data, indent=2, ensure_ascii=False) + "\n", OUT_MD: render_md(data)}
    for rel, text in outputs.items():
        for label, pattern in PRIVATE_CONTENT:
            if pattern.search(text):
                print(f"{rel}: {label} in generated output", file=sys.stderr)
                return 1
    if args.write:
        for rel, text in outputs.items():
            (ROOT / rel).write_text(text, encoding="utf-8")
            host_receipts.register_file(ROOT, rel)
        print(json.dumps({"status": "written", "layers": len(data["layers"]), "winners": data["summary"]["winners"]}))
        return 0
    stale = [rel for rel, text in outputs.items() if not (ROOT / rel).is_file() or (ROOT / rel).read_text(encoding="utf-8") != text]
    if stale:
        print("stale or missing: " + ", ".join(stale) + "; run python3 scripts/component_matrix.py --write, then "
              "python3 scripts/new_host_grand_list.py --write", file=sys.stderr)
        return 1
    print(json.dumps({"status": "passed", "layers": len(data["layers"]), "winners": data["summary"]["winners"]}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
