#!/usr/bin/env python3
"""Build the new-host grand list: every foundation and trading layer with its
recorded winners, their pins against upstream, per-platform E2E state, the
install profile and bootstrap pin that bring each one onto a new machine, and
the hardware tiers of the known hosts.

This is a read-only join. It never selects a winner, changes a verdict, pins a
version or records a receipt. Sources:

- ``catalogs/landscape/component-evidence-matrix.json``: winners, evidence
  class, per-platform ``e2e_state``, open ``executable_now`` gaps and the
  ``needs_host`` lists (itself generated by ``scripts/component_matrix.py``);
- ``catalogs/landscape/{foundation,us-equities}.json``: each layer's decision and each winner's recorded
  basis (``why_selected`` and its ``evidence_refs``), carried in the JSON output only;
- ``catalogs/sota-convergence/manifest-20260923.json``: upstream latest release
  and ``pin_behind_upstream`` per component;
- ``adoption/manifest.json``: install profiles (setup order) and recipes;
- ``adoption/pins-linux-x86_64.json`` and ``adoption/pins-macos-arm64.json``:
  which tools each bootstrap installs from a pinned, checksummed artifact;
- ``adoption/hardware-profiles.json`` and the measured host evidence it cites:
  per-host tiers.

Modes: ``--check`` (default) recomputes both outputs and exits 1 on any
difference from the checked-in files; ``--write`` writes them.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from urllib.parse import urlparse

try:
    from . import host_receipts
    from .validate import PRIVATE_CONTENT
except ImportError:  # running as a plain script, not a package
    import host_receipts
    from validate import PRIVATE_CONTENT

ROOT = Path(__file__).resolve().parent.parent
OUT_JSON = "catalogs/landscape/new-host-grand-list.json"
OUT_MD = "docs/new-host-grand-list.md"
MANIFEST = "catalogs/sota-convergence/manifest-20260923.json"
PLATFORMS = ("linux-wsl2-x86_64", "macos-arm64")
PIN_FILES = {"linux-wsl2-x86_64": "adoption/pins-linux-x86_64.json", "macos-arm64": "adoption/pins-macos-arm64.json"}
LEDGERS = {"foundation": "catalogs/landscape/foundation.json", "us-equities": "catalogs/landscape/us-equities.json"}
# Bootstrap pin ids that name the same component under a different id.
PIN_ALIASES = {"claude-code": {"claude-code", "claude"}, "llama-cpp": {"llama-cpp", "llama.cpp"}}
# Ledger/matrix component ids that appear under a different id in adoption/manifest.json profiles.
ADOPTION_IDS = {
    "nautilustrader": "nautilus-trader", "data-alpaca-py": "alpaca-py", "data-duckdb": "duckdb",
    "data-edgartools": "edgartools", "data-exchange-calendars": "exchange-calendars",
    "foundation-ai-memory": "ai-memory", "foundation-socraticode": "socraticode",
    "candidate:cli-cli": "gh", "candidate:astral-sh-uv": "uv",
}


def load(rel: str):
    return json.loads((ROOT / rel).read_text(encoding="utf-8"))


def github_repo(url):
    """owner/name for a URL whose host is exactly github.com, else None."""
    if not isinstance(url, str):
        return None
    parsed = urlparse(url.strip())
    if parsed.scheme not in ("http", "https") or (parsed.hostname or "").lower() not in ("github.com", "www.github.com"):
        return None
    parts = [part for part in parsed.path.split("/") if part]
    if len(parts) < 2:
        return None
    return (parts[0] + "/" + re.sub(r"\.git$", "", parts[1])).lower()


def repo_key(url) -> str:
    if not isinstance(url, str):
        return ""
    return github_repo(url) or url.strip().rstrip("/").lower()


def manifest_index(manifest: dict) -> dict:
    index = {}
    for section in ("foundation", "trading"):
        for layer in manifest.get(section, []):
            layer_id = layer.get("layer")
            for comp in (layer.get("components") or []) + (layer.get("entries") or []) + (layer.get("candidates") or []):
                if not isinstance(comp, dict):
                    continue
                entry = {
                    "manifest_id": comp.get("id"),
                    "manifest_pin": comp.get("pin"),
                    "upstream_latest": (comp.get("upstream") or {}).get("latest"),
                    "pin_behind_upstream": comp.get("pin_behind_upstream"),
                    "pin_comparison": comp.get("pin_comparison"),
                }
                index[(layer_id, "id", comp.get("id"))] = entry
                key = repo_key(comp.get("repository"))
                if key:
                    index.setdefault((layer_id, "repo", key), entry)
    return index


def profile_index(adoption: dict) -> dict:
    out = {}
    for order, profile in enumerate(adoption.get("profiles", []), start=1):
        for comp in profile.get("component_ids", []):
            out.setdefault(comp, []).append({"order": order, "profile": profile["id"]})
    return out


def pinned_tools() -> dict:
    """Per platform: the pinned tool ids and the GitHub repositories their artifacts come from."""
    out = {}
    for platform, rel in PIN_FILES.items():
        tools = [tool for tool in load(rel).get("tools", []) if isinstance(tool, dict)]
        out[platform] = {"ids": {tool.get("id") for tool in tools},
                         "repos": {github_repo(tool.get("url")) for tool in tools if github_repo(tool.get("url"))},
                         "versions": {tool.get("id"): tool.get("version") for tool in tools},
                         "repo_versions": {github_repo(tool.get("url")): tool.get("version") for tool in tools
                                           if github_repo(tool.get("url"))}}
    return out


def adoption_id(component_id: str) -> str:
    return ADOPTION_IDS.get(component_id, strip_candidate(component_id))


def bootstrap_pin(component_id: str, repository, pins_for_platform: dict):
    """The version the platform's bootstrap installs for this component, or None when it installs none."""
    bare = adoption_id(component_id)
    for name in sorted(PIN_ALIASES.get(bare, {bare})):
        if name in pins_for_platform["ids"]:
            return pins_for_platform["versions"].get(name) or "pinned"
    if repository and repo_key(repository) in pins_for_platform["repos"]:
        return pins_for_platform["repo_versions"].get(repo_key(repository)) or "pinned"
    return None


def is_pinned(component_id: str, repository, pins_for_platform: dict) -> bool:
    return bootstrap_pin(component_id, repository, pins_for_platform) is not None


def ledger_decisions() -> dict:
    out = {}
    for catalog, rel in LEDGERS.items():
        for layer in load(rel).get("layers", []):
            out[(catalog, layer.get("layer_id"))] = layer.get("decision")
    return out


def ledger_winner_basis() -> dict:
    """Each ledger winner's recorded basis, ``why_selected`` and its ``evidence_refs``, keyed by
    ``(catalog, layer_id, component_id)``: why the lane verdict chose it and what evidence that rests on.
    Copied verbatim so the JSON form of the grand list carries it next to the winner."""
    out = {}
    for catalog, rel in LEDGERS.items():
        for layer in load(rel).get("layers", []):
            for winner in layer.get("winners") or []:
                out[(catalog, layer.get("layer_id"), winner.get("component_id"))] = {
                    "why_selected": winner.get("why_selected"),
                    "evidence_refs": list(winner.get("evidence_refs") or []),
                }
    return out


def strip_candidate(component_id: str) -> str:
    return component_id.split(":", 1)[1] if component_id.startswith("candidate:") else component_id


def build_hosts(hw: dict) -> list[dict]:
    """``adoption/hardware-profiles.json`` ``hosts[]``, joined with the measured tiers a
    ``native_proven`` entry's ``.json`` evidence file recommends. Fails loudly (raises
    ``SystemExit``) when such an entry names an evidence file that does not exist, instead of
    silently emitting ``measured_tiers: null``; a ``native_proven`` entry whose evidence is
    prose (for example a hosted-CI-run citation, not a report path) is not held to that check.

    Every host's own ``measured`` block (arbitrary shape -- a plain hardware_profile.py
    measurement, or something like a hosted runner's ``measured.mlx_smoke``) is carried
    through so it reaches the generated JSON and Markdown. That block can live directly on
    the ``hosts[]`` entry (as the shipped ``github-macos-15-arm64-runner`` entry has it) or,
    for an entry ``scripts/hardware_profile.py --record-host`` wrote, only in the evidence
    file's own ``measured`` key (that command does not copy it onto the entry): an entry's
    own ``measured`` wins when both are present, else the evidence file's is used."""
    hosts = []
    for host in hw.get("hosts", []):
        tiers = None
        measured = host.get("measured")
        evidence = host.get("evidence")
        if host.get("evidence_class") == "native_proven" and isinstance(evidence, str) and evidence.endswith(".json"):
            path = ROOT / evidence
            if not path.is_file():
                raise SystemExit(
                    f"new_host_grand_list: hosts[] entry {host.get('id')!r} is native_proven and names "
                    f"evidence file {evidence!r}, which does not exist; record it (scripts/hardware_profile.py "
                    "--record-host) or fix the evidence path in adoption/hardware-profiles.json instead of "
                    "leaving a dangling reference")
            evidence_doc = json.loads(path.read_text(encoding="utf-8"))
            tiers = evidence_doc.get("recommended")
            if measured is None:
                measured = evidence_doc.get("measured")
        hosts.append({
            "id": host.get("id"),
            "label": host.get("label"),
            "evidence_class": host.get("evidence_class"),
            "assumptions": host.get("assumptions"),
            "measured_tiers": tiers,
            "measured": measured,
            "sizing_arithmetic": host.get("sizing_arithmetic"),
        })
    return hosts


def build() -> dict:
    matrix = load("catalogs/landscape/component-evidence-matrix.json")
    mindex = manifest_index(load(MANIFEST))
    adoption = load("adoption/manifest.json")
    profiles = profile_index(adoption)
    recipes = adoption.get("recipe_map", {})
    pins = pinned_tools()
    decisions = ledger_decisions()
    basis = ledger_winner_basis()
    hw = load("adoption/hardware-profiles.json")

    layers = []
    qualified_models = []
    for row in matrix["rows"]:
        winners = []
        for winner in row.get("winners", []):
            cid = winner["component_id"]
            bare = strip_candidate(cid)
            m = (mindex.get((row["layer_id"], "id", cid)) or mindex.get((row["layer_id"], "id", bare))
                 or mindex.get((row["layer_id"], "repo", repo_key(winner.get("repository")))) or {})
            platforms = {}
            for platform in PLATFORMS:
                state = (winner.get("platforms") or {}).get(platform) or {}
                platforms[platform] = {
                    "e2e_state": state.get("e2e_state"),
                    "bootstrap_pinned": is_pinned(cid, winner.get("repository"), pins[platform]),
                    "bootstrap_version": bootstrap_pin(cid, winner.get("repository"), pins[platform]),
                }
                for qm in state.get("qualified_models") or []:
                    qualified_models.append({
                        "catalog": row["catalog"], "layer_id": row["layer_id"], "component_id": cid,
                        "platform": platform, **qm,
                    })
            winners.append({
                "component_id": cid,
                "repository": winner.get("repository"),
                "pin": winner.get("pin"),
                "evidence_class": winner.get("evidence_class"),
                "upstream_latest": m.get("upstream_latest"),
                "pin_behind_upstream": m.get("pin_behind_upstream"),
                "manifest_joined": bool(m),
                "install_profiles": [p["profile"] for p in profiles.get(adoption_id(cid), [])],
                "recipe": recipes.get(adoption_id(cid)),
                "platforms": platforms,
                "why_selected": basis.get((row["catalog"], row["layer_id"], cid), {}).get("why_selected"),
                "evidence_refs": basis.get((row["catalog"], row["layer_id"], cid), {}).get("evidence_refs", []),
            })
        layers.append({
            "catalog": row["catalog"],
            "layer_id": row["layer_id"],
            "title": row["title"],
            "decision": decisions.get((row["catalog"], row["layer_id"])),
            "verdict_status": row.get("verdict_status"),
            "independent_review": row.get("independent_review"),
            "open_executable_now_gaps": row.get("open_executable_now_gaps"),
            "open_gaps": row.get("open_gaps"),
            "winners": winners,
        })

    hosts = build_hosts(hw)

    qualified_models.sort(key=lambda q: (q["catalog"], q["layer_id"], q["component_id"], q["platform"],
                                         q.get("model_id") or "", q.get("receipt_path") or ""))

    winners_all = [w for layer in layers for w in layer["winners"]]
    summary = {
        "layers": {"foundation": sum(1 for l in layers if l["catalog"] == "foundation"),
                   "us-equities": sum(1 for l in layers if l["catalog"] == "us-equities")},
        "winners": len(winners_all),
        "winner_count_unit": "layer-winner pairs (a component that wins several layers counts once per layer)",
        "distinct_components": len({adoption_id(w["component_id"]) for w in winners_all}),
        "pins_behind_upstream": sorted({adoption_id(w["component_id"]) for w in winners_all if w["pin_behind_upstream"] is True}),
        "not_joined_to_manifest": sorted({w["component_id"] for w in winners_all if not w["manifest_joined"]}),
        "e2e_accepted": {p: sum(1 for w in winners_all if w["platforms"][p]["e2e_state"] == "accepted") for p in PLATFORMS},
        # host_verified is accepted on the strength of a host receipt (scripts/component_matrix.py),
        # and needs_host excludes it; count it separately so the headline pairs add up to the winners.
        "e2e_host_verified": {p: sum(1 for w in winners_all if w["platforms"][p]["e2e_state"] == "host_verified")
                              for p in PLATFORMS},
        "bootstrap_pinned": {p: sorted({w["component_id"] for w in winners_all if w["platforms"][p]["bootstrap_pinned"]}) for p in PLATFORMS},
        "needs_host": {p: len(matrix.get("summary", {}).get("needs_host", {}).get(p, [])) for p in PLATFORMS},
    }
    return {
        "schema_version": 1,
        "scope": ("Read-only join of the recorded layer winners, their pins against upstream, per-platform E2E state, "
                  "install profiles, bootstrap pins and host hardware tiers, for setting up a new WSL2 or macOS host. "
                  "It selects nothing and changes no verdict."),
        "sources": {
            "matrix": "catalogs/landscape/component-evidence-matrix.json",
            "ledgers": LEDGERS,
            "manifest": MANIFEST,
            "profiles": "adoption/manifest.json",
            "bootstrap_pins": PIN_FILES,
            "hardware": "adoption/hardware-profiles.json",
        },
        "setup_order": [{"order": i, "profile": p["id"], "label": p.get("label"), "component_ids": p.get("component_ids", [])}
                        for i, p in enumerate(adoption.get("profiles", []), start=1)],
        "hosts": hosts,
        "layers": layers,
        "qualified_models": qualified_models,
        "summary": summary,
    }


def tier_value(value):
    """Reduce a labelled-projection arithmetic string to its result, e.g.
    'vram_gb=24 >= 20 -> large-32b-q4' -> 'large-32b-q4'; 'min(16, 32 - 2) = 16' -> '16';
    'min(16, 60 - 2) = 16 (nproc inside WSL is the .wslconfig processors=60)' -> '16' (a
    trailing parenthetical explanatory note, itself possibly containing '=', is dropped
    first; catalog PR #125 finding). A string with no trailing note still takes the result
    after the *last* '=' (for example 'max(6, round(...)=24.8), min(24.8, 32) = 24.8' ->
    '24.8', or 'cap = min(16, 30)' -> 'min(16, 30)': that trailing '(...)' is glued directly
    onto a preceding token with no space, so it is part of the result expression itself, not
    a separate note, and must not be dropped)."""
    if not isinstance(value, str):
        return value
    if "->" in value:
        return value.rsplit("->", 1)[1].strip()
    core = value
    stripped = core.rstrip()
    if stripped.endswith(")"):
        depth = 0
        open_index = None
        for index in range(len(stripped) - 1, -1, -1):
            if stripped[index] == ")":
                depth += 1
            elif stripped[index] == "(":
                depth -= 1
                if depth == 0:
                    open_index = index
                    break
        # Only a trailing "(...)" set off by a space (e.g. "16 (nproc ...)") is a separate
        # explanatory note to drop; one glued directly to a preceding token (e.g.
        # "min(16, 30)", no space before "(") is part of the expression and stays.
        if open_index is not None and open_index > 0 and stripped[open_index - 1] == " ":
            core = stripped[:open_index].rstrip()
    if "=" in core:
        return core.rsplit("=", 1)[1].strip()
    return core


def md_cell(value) -> str:
    return str(value if value not in (None, "") else "—").replace("|", "\\|").replace("\n", " ")


def measured_cell(measured) -> str | None:
    """Compact one-line summary of a hosts[] entry's ``measured`` block (arbitrary shape:
    a plain hardware_profile.py measurement, or something like the GitHub-hosted macOS
    runner's ``measured.mlx_smoke`` sub-object), or None when there is nothing measured."""
    if not isinstance(measured, dict) or not measured:
        return None
    parts = []
    for key in ("cpu_brand", "cores", "unified_memory_gb", "effective_ram_gb"):
        if measured.get(key) not in (None, ""):
            parts.append(f"{key}={measured[key]}")
    smoke = measured.get("mlx_smoke")
    if isinstance(smoke, dict) and smoke:
        smoke_bits = [f"{smoke['model']}@{smoke['revision'][:7]}" if smoke.get("model") and smoke.get("revision")
                      else smoke.get("model")]
        if smoke.get("tokens_per_second") is not None:
            smoke_bits.append(f"{smoke['tokens_per_second']} tok/s")
        if smoke.get("generation_tokens") is not None:
            smoke_bits.append(f"{smoke['generation_tokens']} tokens")
        parts.append("mlx_smoke: " + ", ".join(str(b) for b in smoke_bits if b))
    return "; ".join(parts) if parts else None


def gap_cell(layer: dict) -> str:
    """'executable now / all open' from the gap crosswalk, so a layer whose only open gap needs a
    login, hardware or a user decision shows '0 / 1', not '0'."""
    return f"{md_cell(layer.get('open_executable_now_gaps'))} / {md_cell(layer.get('open_gaps'))}"


def render_md(data: dict) -> str:
    s = data["summary"]

    def accepted_line(platform):
        host_verified = s["e2e_host_verified"][platform]
        return (f"{s['e2e_accepted'][platform] + host_verified} "
                f"({host_verified} of them `host_verified` on a host receipt)")

    lines = [
        "# New-host grand list",
        "",
        "Generated by `scripts/new_host_grand_list.py` from the component evidence matrix, the layer ledgers, "
        f"`{MANIFEST}`, `adoption/manifest.json`, the bootstrap pin files and `adoption/hardware-profiles.json`. "
        "Do not edit by hand; run `python3 scripts/new_host_grand_list.py --write`. It selects nothing: winners and "
        "verdicts change only through the lane re-record, pins only through their qualification.",
        "",
        f"Layers: {s['layers']['foundation']} foundation, {s['layers']['us-equities']} trading. Winners: {s['winners']} "
        f"layer-winner pairs ({s['distinct_components']} distinct components). Pairs accepted end to end: "
        f"{accepted_line('linux-wsl2-x86_64')} on WSL2, {accepted_line('macos-arm64')} on macOS. Distinct "
        f"components pinned behind upstream: {len(s['pins_behind_upstream'])}. Pairs a new host still has to prove: "
        f"{s['needs_host']['linux-wsl2-x86_64']} on WSL2, {s['needs_host']['macos-arm64']} on macOS "
        "(the `needs_host` lists in `catalogs/landscape/component-evidence-matrix.json`).",
        "",
        "## How to set up a host",
        "",
        "1. Follow [`adoption/bootstrap.md`](../adoption/bootstrap.md) from a pinned clone (step 0) through native sign-in.",
        "2. Run `python3 scripts/hardware_profile.py` and compare its tiers with the host table below.",
        "3. Install the profiles in the order below; each bootstrap installs only the tools in its pin file.",
        "4. Record what ran with [`docs/contributing-evidence.md`](contributing-evidence.md) (`scripts/host_receipts.py`).",
        "",
        "## Setup order (install profiles)",
        "",
        "| Order | Profile | Components |",
        "| --- | --- | --- |",
    ]
    for p in data["setup_order"]:
        lines.append(f"| {p['order']} | `{p['profile']}`: {md_cell(p['label'])} | {', '.join('`' + c + '`' for c in p['component_ids'])} |")
    lines += ["", "## Hosts and hardware tiers", "",
              "| Host | Evidence | Generation tier | Semantic-RAG tier | Concurrency cap | Measured |",
              "| --- | --- | --- | --- | --- | --- |"]
    for h in data["hosts"]:
        t = h.get("measured_tiers") or {}
        a = h.get("sizing_arithmetic") or {}
        gen = t.get("local_generation_model_tier") or tier_value(a.get("local_generation_model_tier"))
        rag = t.get("embedding_semantic_rag_tier") or tier_value(a.get("embedding_semantic_rag_tier"))
        cap = t.get("workflow_concurrency_cap") or tier_value(a.get("workflow_concurrency_cap"))
        lines.append(f"| {md_cell(h['label'])} | {md_cell(h['evidence_class'])} | {md_cell(gen)} | {md_cell(rag)} | "
                     f"{md_cell(cap)} | {md_cell(measured_cell(h.get('measured')))} |")
    lines += ["", "## Qualified local models", "",
              "Locally-run model weights a host receipt recorded qualifying on a runtime component's winner row "
              "(`scripts/host_receipts.py record --qualified-model`). This is per-host, per-runtime evidence, not a "
              "verdict: it never marks anything `accepted` by itself, and the platform-status flip rule "
              "(`scripts/platform_status.py`) still governs whether that runtime's own row may claim more.", "",
              "| Model | Revision | Runtime | Version | Host | Platform | Result | Receipt |",
              "| --- | --- | --- | --- | --- | --- | --- | --- |"]
    if not data["qualified_models"]:
        lines.append("| — | — | — | — | — | — | — | — |")
    else:
        for q in data["qualified_models"]:
            lines.append(f"| {md_cell(q.get('model_id'))} | {md_cell(q.get('revision'))} | {md_cell(q.get('runtime'))} "
                         f"| {md_cell(q.get('runtime_version'))} | {md_cell(q.get('host_id'))} | {md_cell(q.get('platform'))} "
                         f"| {md_cell(q.get('result'))} | {md_cell(q.get('receipt_path'))} |")
    for catalog, title in (("foundation", "Foundation layers"), ("us-equities", "Trading layers (north star)")):
        lines += ["", f"## {title}", "",
                  "| Layer | Decision | Winner | Pin (upstream) | Evidence | WSL2 | macOS | Installed by | Open gaps (executable now / all) |",
                  "| --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
        for layer in (l for l in data["layers"] if l["catalog"] == catalog):
            for i, w in enumerate(layer["winners"] or [None]):
                head = f"{md_cell(layer['title'])} | {md_cell(layer['decision'])}" if i == 0 else " | "
                if w is None:
                    lines.append(f"| {head} | — | — | — | — | — | — | {gap_cell(layer)} |")
                    continue
                pin = md_cell(w["pin"])
                if w["pin_behind_upstream"] is True and w["upstream_latest"]:
                    pin += f" (behind {md_cell(w['upstream_latest'])})"
                cells = []
                for p in PLATFORMS:
                    st = w["platforms"][p]
                    cells.append(md_cell(st["e2e_state"]) + (f", bootstrap {st['bootstrap_version']}" if st["bootstrap_pinned"] else ""))
                gaps = gap_cell(layer) if i == 0 else ""
                lines.append(f"| {head} | `{w['component_id']}` | {pin} | {md_cell(w['evidence_class'])} | {cells[0]} | {cells[1]} | "
                             f"{md_cell(', '.join(w['install_profiles']))} | {gaps} |")
    lines += ["", "\"bootstrap X\" means the platform's bootstrap installs version X from a pinned, checksummed artifact; "
              "it can differ from the ledger pin in the Pin column (the ledger records what a verdict was measured on, the "
              "bootstrap what a new host installs). "
              "An E2E state of `accepted` is scoped to the recorded host; a new host proves its own."]
    counts = {}
    for layer in data["layers"]:
        counts[layer["decision"]] = counts.get(layer["decision"], 0) + 1
    tally = ", ".join(f"`{k}` {v}" for k, v in sorted(counts.items(), key=lambda kv: (-kv[1], str(kv[0]))))
    lines += ["", "## What a winner means", "",
              "A winner is the layer's recorded choice from its lane verdict, shown with its evidence class. It is not a "
              "claim that the component is the best in its field. The Decision column is the layer ledger's decision "
              f"({tally} across {len(data['layers'])} layers); a `keep_but_compare` row keeps its incumbent while the "
              "comparison the row names is still owed. Each winner's recorded basis, its `why_selected` text and its "
              "`evidence_refs`, is carried in the JSON form of this list and in the layer ledgers, together with the "
              "layer's limitations and open gaps."]
    lines += ["", "## How to update this page", "",
              "Generated, not hand-edited. After any change to the component evidence matrix (host receipts, "
              "decisions, verdict re-records), the layer ledgers, `" + MANIFEST + "`, `adoption/manifest.json`, the "
              "bootstrap pin files or `adoption/hardware-profiles.json`, run "
              "`python3 scripts/component_matrix.py --write` and then `python3 scripts/new_host_grand_list.py --write`, "
              "and commit the outputs. `--check` runs in CI."]
    if s["not_joined_to_manifest"]:
        lines += ["", "Winners without a manifest row (no upstream comparison shown): "
                  + ", ".join("`" + c + "`" for c in s["not_joined_to_manifest"]) + "."]
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="exit 1 if the checked-in outputs differ (default)")
    mode.add_argument("--write", action="store_true", help="write the outputs")
    args = parser.parse_args(argv)
    data = build()
    outputs = {OUT_JSON: json.dumps(data, indent=2, ensure_ascii=False) + "\n", OUT_MD: render_md(data)}
    for rel, text in outputs.items():
        for label, pattern in PRIVATE_CONTENT:
            if pattern.search(text):
                print(f"{rel}: {label} in generated output", file=sys.stderr)
                return 1
    if args.write:
        for rel, text in outputs.items():
            (ROOT / rel).write_text(text, encoding="utf-8")
            host_receipts.register_file(ROOT, rel)
        print(json.dumps({"status": "written", "layers": len(data["layers"]), "winners": data["summary"]["winners"]}))
        return 0
    stale = [rel for rel, text in outputs.items() if not (ROOT / rel).is_file() or (ROOT / rel).read_text(encoding="utf-8") != text]
    if stale:
        print("stale or missing: " + ", ".join(stale) + "; run python3 scripts/component_matrix.py --write, then "
              "python3 scripts/new_host_grand_list.py --write", file=sys.stderr)
        return 1
    print(json.dumps({"status": "passed", "layers": len(data["layers"]), "winners": data["summary"]["winners"]}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
