# Source: https://github.com/systemd/systemd/blob/b3d8fc43e9cb531d958c17ef2cd93b374bc14e8a/man/sysctl.d.xml#L45 ; https://github.com/microsoft/WSL2-Linux-Kernel/blob/14794180686c2fb6307fbe359c359bec765249f3/Documentation/admin-guide/sysctl/vm.rst#L959
vm.swappiness = 10
